### ISSUE TITLE
options.DOMParser is not optional

### ISSUE THREAD

**Issue by lzilioli** [notable/dumper#34]
- **File Extension**: `.html`
- **Dumper Version**: 2.0.1

### Current behavior

```
const source: string[] = [
	...await glob.sync(`**/*.html`),
];
Dumper.dump ({
	source,
	async dump ( note: Note ): Promise<void> {
		console.log('note dumped', note);
		// Do something with each given note object...
	}
});
```

console error =>
```
(node:34069) UnhandledPromiseRejectionWarning: TypeError: options.parser is not a constructor
    at htmlParser (./build/server/index.js:1488:32)
(...stack redacted...)
```

### Expected behavior

Expected to start getting some note dumped log outputs

per the readme, DOMParser should not be something I MUST override

```
interface Options {
  DOMParser?: DOMParser,
  source: string | string[],
  dump ( note: Note ): void | Promise<void>
}
```

This file exhibits the issue:

[index.txt](https://github.com/notable/dumper/files/5845692/index.txt)

(note I changed the extension from html to txti in order for github to allow me to upload it)

**Comment by fabiospampinato** [comment]
It is optional, if you are in a browser environment. See https://github.com/notable/dumper/commit/fab724ecf577c7bd577c67950f004b265085d0b7

**Comment by lzilioli** [comment]
@fabiospampinato what can I specify here if using in a node-like environment where the package errors out and no such global DOMParser exists?

**Comment by fabiospampinato** [comment]
@lzilioli you need something that works similarly enough to the DOMParser you have on the web.

You can probably get something like that from `jsdom`.

You can also take a look at how this library runs it's [tests](https://github.com/notable/dumper/blob/2c4338fe4dcd1c9f954c7f29a196468089167237/test/index.js#L20-L240).
