### ISSUE TITLE
An error occurred: File size (3666700614) is greater than possible Buffer: 2147483647 bytes

### ISSUE THREAD

**Issue by markcarroll** [notable/dumper#9]
- **OS Version**: darwin 18.7.0
- **Notable Version**: v1.7.3

```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3666700614) is greater than possible Buffer: 2147483647 bytes
    at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:274:11)
```

**Comment by markcarroll** [comment]
Yep, thanks. I did just that.

**Comment by fabiospampinato** [comment]
I'm reopening this as I think eventually we should support arbitrarily sized files.

**Comment by fabiospampinato** [comment]
Closing this in favor of #22.

The library now throws a regular error for huge files.
